# Generated by Django 4.1.7 on 2023-03-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group',
            new_name='chat_group',
        ),
    ]
